3Hren/msgpack-rust

- src/decode.rs
- src/encode.rs
Implement the `Error` trait for all error types in `rmp::{encode,decode}`. Descriptions could be better but I don't understand the different error types well enough.
> Implement `std::error::Error` trait for error types

- src/decode.rs
- src/encode.rs
The following work is pending:
> Interruption safety

- CHANGELOG.md
- src/decode.rs
- src/encode.rs
- tests/func/mod.rs
- tests/func/rserialize.rs
- tests/func/serde.rs
> Extend Encoder/Decoder interface

- README.md
> Docs(readme): update.

- CHANGELOG.md
- rmp/src/value.rs
- rmp/tests/value.rs
> Display trait for Value

- rmp-serde/src/decode.rs
And a very synthetic benchmark:
```rust
#![feature(test)]
extern crate test;
extern crate serde;
extern crate rmp_serde;
use serde::{Serialize, Deserialize};
use test::{Bencher};
#[bench]
fn bench_strings_1000(bencher: &mut Bencher) {
bench_strings(bencher, 1000)
}
#[bench]
fn bench_strings_5000(bencher: &mut Bencher) {
bench_strings(bencher, 5000)
}
#[bench]
fn bench_strings_10000(bencher: &mut Bencher) {
bench_strings(bencher, 10000)
}
fn bench_strings(bencher: &mut Bencher, size: usize) {
let mut vec = Vec::new();
for _ in 0..size {
vec.push("abcdefghijklmnopqrstuvwxyz".to_string());
}
let mut buf = Vec::new();
{
let mut serializer = rmp_serde::Serializer::new(&mut buf);
vec.serialize(&mut serializer).unwrap();
}
bencher.iter(|| {
<Vec<String>>::deserialize(&mut …
```
> Reuse Deserializer::buf on every read_str and read_bin_data call

- CHANGELOG.md
- README.md
- rmp/src/value.rs
- rmp/tests/value.rs
> Add convenient Value conversion methods

- rmp-serde/src/encode.rs
- rmp-serde/src/lib.rs
- rmp-serde/tests/se.rs
> feat: impl Serialize for Value

- rmp-serde/src/lib.rs
- rmp-serde/tests/de.rs
- rmp/src/value.rs
> implement `serde::Deserialize` for Value

- rmp-serde/src/decode.rs
- rmp-serde/src/encode.rs
- rmp-serde/tests/de_macro.rs
- rmp-serde/tests/round.rs
- rmp-serde/tests/se_macro.rs
Hey, this PR should fixup the failing tests, there's still one disabled though. There was a weird case with enums containing newtypes that I sorta bodged. Any thoughts?
> Fix failing tests from pull request #83

- rmp-serde/src/decode.rs
- rmp-serde/tests/common/de.rs
- rmp/src/decode/mod.rs
See test_deserialize_numeric for usage example.
> fix: deserialize numeric type in Deserializer::deserialize

- README.md
> docs: fix errors in README

- .gitignore
- .travis.yml
- rmp-serde-tests/Cargo.toml
- rmp-serde-tests/tests/decode.rs
- rmp-serde/Cargo.toml
- rmp-serde/src/decode.rs
- rmp-serde/src/encode.rs
- rmp-serde/src/lib.rs
- rmp-serde/tests/decode.rs
- rmp-serde/tests/encode.rs
- rmpv-tests/Cargo.toml
- rmpv-tests/tests/decode.rs
- rmpv-tests/tests/encode.rs
- rmpv-tests/tests/round.rs
- rmpv/Cargo.toml
- rmpv/src/ext.rs
- rmpv/src/lib.rs
> feat: upgrade serde to 1.0

- rmpv-tests/tests/de_ref.rs
- rmpv/src/ext.rs
> feat: zero-copy deserializer for `ValueRef`

- rmp/CHANGELOG.md
- rmp/src/decode/mod.rs
- rmp/src/decode/str.rs
- rmp/tests/func/decode/string.rs
@cmbrandenburg, this is the best I can invent right now. Resolves #69.
> feat: add zero-copy string decode

- .travis.yml
> ci: resurrect code coverage

- README.md
I am not sure if this change is reasonable. If is is not, I highly recommend clarifying the sentence I want the change to be applied on.
> Fixed error in zero-copy description (?)

- rmp-serde/src/decode.rs
- rmp-serde/tests/round.rs
- rmp/src/decode/mod.rs
> Fix reading Some(enum)

- rmp/Cargo.toml
Signed-off-by: Robert-André Mauchin <zebob.m@gmail.com>
> Bump num-traits to 0.2

- .travis.yml
- rmpv/benches/value.rs
This may allow us to judge the performance impact of the changes in #221.
> Fix benches

- rmp-serde/Cargo.toml
- rmp-serde/src/decode.rs
- rmp-serde/src/encode.rs
- rmp-serde/tests/round.rs
> Revert is_human_readable

- rmp-serde/CHANGELOG.md
- rmp-serde/src/decode.rs
- rmp-serde/tests/decode.rs
> add depth limit for deserializer

- rmp-serde/src/config.rs
- rmp-serde/src/decode.rs
- rmp-serde/src/encode.rs
- rmp-serde/tests/encode_derive.rs
- rmp-serde/tests/round.rs
This is a continuation of https://github.com/3Hren/msgpack-rust/pull/285
> Use string variants
