3Hren/msgpack-rust

src/decode.rs
src/encode.rs
tests/func/decode/decoder.rs

Generalized integers decoding

---

src/decode.rs

Force `BigEndianRead` trait to be sized.

---

rmp-serde/src/encode.rs
rmp-serde/src/lib.rs
rmp-serde/tests/deserializer.rs
rmp-serde/tests/serializer.rs

Struct encoding policy

---

rmp-serde/src/decode.rs
rmp-serde/src/encode.rs

Made rmp-serde stack-safe

---

rmp/Cargo.toml

Right now byteorder 0.4.2 appears to work fine without code changes.
And 0.3.x will (of course) continue to work.
We want to expand the allowed versions so users of this crate can avoid
pulling in (unneededly) multiple versions of the same create (byteorder
uses libc)
I've expanded the version match to allow any '0.*' version to avoid
repeating this commit in the future, but I'm OK if you'd like a more
restricted version (does cargo allow '<0.5 && >=0.3'?).

misc(rmp): allow use of newer byteorder dep

---

rmp-serde/Cargo.toml
rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/tests/de_macro.rs

I was trying to drop rmp-serde into a project where I was already using serde with serde-json, and discovered that it wouldn't work.  So, I updated rmp to work with the most recent version of serde (0.7).
Basically, it involved renaming a few things and adding in a couple of new error conditions.

Made rmp-serde compatible with serde 0.7

---

rmp-serde/src/decode.rs

So it's possible to preallocate things in `Deserialize` implementations.

Implement size_hint function for SeqVisitor and MapVisitor

---

rmp-serde/src/encode.rs

Right now if there is a struct with no elements it's being serialized as an array, which is fine with the default way of handling structs, which is as an array.  If, however, you want to serialize a struct as a map (as I do) then this causes inconsistencies.

Switch unit structs to using the same serialization mechanism as other structs

---

.travis.yml
rmp-serde/Cargo.toml
rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/src/lib.rs

Tried to stick as close to the original implementation as possible, but I did not implement the depth limit.
There are no more default impls for the traits, so these were
implemented using the suggested defaults of passing to other handlers
where it made sense.

Update to the serde 0.8 API

---

rmp-serde/tests/de_macro.rs
rmp-serde/tests/round.rs
rmp-serde/tests/se_macro.rs

There's actually at least two failing tests that identify problems I've run into.
They didn't seem to be enabled in Travis under the old config, but will run and fail under this config from what I can tell.
This appears to follow the work in #81

Fixup the macro based tests for the new serde_derive

---

rmp-serde/src/lib.rs

This adds convenience to_vec() and from_slice() functions for rmp-serde.
The naming is in line with other serde modules (serde_json has to_string / from_str, and most other modules have something similar).
Now you can just do this:
```rust
let ser = rmp_serde::to_vec(&some_struct).unwrap();
let val = rmp_serde::from_slice::<MyType>(&ser).unwrap();
```

serde: Add convenience to_vec / from_slice (de)serialization functions.

---

rmp-serde/src/decode.rs
rmp-serde/src/lib.rs
rmpv-tests/tests/round.rs

Resolves another feature of #121 - zero-copy deserialization from byte arrays.
For example, when `Deserialize` for `ValueRef` lands, it will be possible to unpack `[u8]` into `ValueRef` without need of `rmpv::decode::read_value_ref`.

feat: zero-copy deserializer

---

rmp-serde/src/decode.rs

Hi.
https://github.com/rust-lang/rust/pull/42125 is going to fix some holes in `rustc`'s privacy checker.
Unfortunately, it can break code sometimes.
`crates.io` testing found 3 unexpected regressions, including this crate.
This PR updates the code to build successfully with https://github.com/rust-lang/rust/pull/42125

Fix build on nightly rustc

---

rmp-serde/src/decode.rs

self-explanatory - tests fail to build on nightly without this change

fix build by making ReadReader public

---

rmpv/tests/decode.rs

I was reading through code base as a Rust learning exercise and added some more test coverage.
This gives at least normal case coverage for everything in /rmpv/src/decode/value.rs, with the exception of `Marker::Reserved`.

Finishing Coverage for /rmpv/src/decode/value.rs

---

rmpv/src/lib.rs
rmpv/tests/decode_ref.rs

Since `ValueRef` has a `to_owned()` method, it makes sense for `Value` to have an `as_ref()` method.

feat: Add as_ref() to Value and Utf8String

---

rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/src/lib.rs
rmp-serde/tests/round.rs

Revival of #133 
Related to #114 (or resolve it?), and [TODO comment](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/src/encode.rs#L68)
I've excluded style-changing from #133 
This PR introduces `StructMapWriter` and its constructor, as discussed in https://github.com/3Hren/msgpack-rust/issues/114#issuecomment-286353371
cc: @semtexzv

Serialize struct as a map

---

rmp-serde/src/decode.rs

Added some docs for the `Error` enum.

chore: document the decode 'Error' enum

---

rmp-serde/src/lib.rs
rmp-serde/tests/encode.rs

Allow to construct from str and bytes with UTF-8 validation.
Closes #143.

feat: implement Serialize for Raw and RawRef

---

rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/tests/decode_derive.rs
rmp-serde/tests/encode_derive.rs
rmp-serde/tests/round.rs

Deserialization fails whenever one enum is inside another untagged enum (see #148 for details). The root problem is that untagged deserialization uses `ContentDeserializer` and `ContentRefDeserializer`, which have unmet expectations:
1. A Unit variant is encoded either as a string or as a map from variant type to `unit`
2. A Tuple, NewType, or Struct variant is encoded as a map from variant type to associated data
3. A Struct variant's associated data must be encoded as a map
This PR fixes problems 1 and 2. A sibling PR on serde (https://github.com/serde-rs/serde/pull/1093)  fixes problem 3 by allowing sequence-encoded associated data for struct variants. As far as I can tell, there is no way to fix problem 3 without touching serde.
**Problem 1 Fix:** Update unit variant encoding from …

Fix error when deserializing untagged enum

---

rmp/src/decode/str.rs
rmp/tests/func/decode/array.rs
rmp/tests/func/decode/sint.rs
rmp/tests/func/decode/string.rs

Related to https://github.com/rust-lang/rust/issues/47640.
Closes #157.

fix: weaken cursor restrictions in tests

---

rmp-serde/Cargo.toml

This helps development, and will be removed by Cargo prior to publishing.

Use rmp from the same workspace when available

---

rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/tests/encode_derive.rs
rmp-serde/tests/round.rs

I've just run into this problem using `rmp_serde`.
Right now, unit structs like `struct Nothing;` are encoded as an empty sequence `[]`, but decoding only ever treats sequences like `[]` as tuple-structs. A round trip for `struct Nothing;` will always fail.
Two solutions I can think of for this failure:
- Change encoding to have unit structs as `nil`, matching what the decoder does
- Change the decoder to care whether `deserialize_unit` or `deserialize_seq` was called, and then if `deserialize_unit` was called, treat `[]` as a unit.
This implements option 1 - a test case is included, and the existing test for the expected serialized bytes is modified.
Fixes #159.

rmp-serde: Fix unit struct round trip

---

rmp-serde/src/ext.rs
rmp-serde/tests/encode_derive.rs
rmp-serde/tests/round.rs

Fixes #201.
This changes the ext encoders to be consistent with `Serializer` when encoding enum struct variants. Now both encode enum variants as a map `{idx => data}`, rather than an array `[idx, data]`.
Includes two round-trip tests using each ext encoder, and one using Serializer to ensure this continues to function.

fix: error reading enum with struct-like variants 

---

rmp-serde/CHANGELOG.md
rmpv/CHANGELOG.md

I looked through all commits since the last modifications to each CHANGELOG file. This should include everything that's changed the API or behavior.

Update CHANGELOGs with API changes

---

rmp-serde/src/config.rs
rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/tests/round.rs

Submitting this after #207 was merged.
Adds a config option for encoding enums variant names as strings. Does not change any defaults.
Notably, this does not change `rmp_serde::to_vec_named`. That remains encoding struct fields names as strings, but enum variants as integers.
Fixes #172. Supersedes and closes #154.

Add configuration option for writing enum variants as strings

---

rmp/src/encode/mod.rs
rmp/tests/func/encode/ext.rs

The timestamp extension is using `-1` as identifier, support such negative values.
Closes #174.

Allow timestamp extension

---

rmp-serde/src/encode.rs

Just a typo I encountered reading the docs.
Thanks

Typo in a docstring.

---

rmpv/benches/value.rs
rmpv/src/decode/value.rs
rmpv/src/decode/value_ref.rs
rmpv/tests/decode.rs

No more vector pre-allocation if the data size is not known in advance. See discussion in #151.
Fixes #151 / RUSTSEC-2017-0006.

Fix unchecked vector pre-allocation

---

rmpv/src/lib.rs
rmpv/tests/value.rs

Consider the use case of json data.
Here is an implementation of val["key"] indexing of maps, and some tests which show results similar to the existing tests for indexing arrays.
This is incomplete (it doesn't support String as an index, among others).
It's verbose for the sake of discussion, and would be more consistent with existing code if it used iterators.
As it stands, this is just an example as a suggestion.

square bracket indexing of maps (e.g. val["key"])

---

rmpv/src/lib.rs
rmpv/tests/value.rs

First shot at https://github.com/3Hren/msgpack-rust/issues/167.
This creates a wrapper type (all names non-final, of course) together with a `From` impl for `Value`. If this is done, we should make all function that take a `Value` take a `T: Into<Value>` instead, so we can directly pass the wrapper type instead having to call `.into()` on it beforehand.
This is a non-breaking change as far as I can see.
I've not connected all the dots, I wanted to hear what you think. I'll offer another alternative at the issue I opened.

[WIP] Provide blanket From impls for homogeneous collections

---

rmpv/src/lib.rs
rmpv/tests/value.rs

Closes https://github.com/3Hren/msgpack-rust/issues/227.
Some comments:
* I didn't do formatting, since there's no `rustfmt.toml`. When the code is ready to be accepted I'll add a commit where I'll manually try to style things similar to the rest of the code
* When implementing nontrivial `TryFrom` things, I just looked at what `as_*` methods are available and mimicked that. I don't fully understand the thought behind it (e.g. I could surely imagine `ValueRef::as_i64` existing, or `Value::as_f32`), but since this is more of a "convenience implementation", I figured I'd stay with consistency.
* I didn't go overboard with tests, since everything's either trivial or refers to already existing implementations (such as `as_f64`). Let me know if more is desirable. Also, there is no …

Implement TryFrom for Value and ValueRef

---

rmpv/src/lib.rs
rmpv/tests/value.rs

I missed that with the last PR, but it's actually the most important part imho :)
It might also be implemented for `Utf8String`, but it would make most sense with `type Error = (Vec<u8>, Uf8Error)`, and I wasn't sure if you wanted to expose the internal details of this type.
Let me know what you think :)

Implement TryInto<String> for Value

---

rmp-serde/src/decode.rs
rmp-serde/src/encode.rs

This makes using [serde-diff](https://docs.rs/serde-diff) possible, which has [special code-paths](https://github.com/amethyst/serde-diff/blob/master/src/lib.rs#L307:L307)
to pre-count elements that otherwise would be generated lazily.
Currently, using serge-diff with Msgpack is not possible directly, as msgpack-rust incorrectly reports that it is human readable. The latter is the default implementation of the [`serde::Serializer`](https://docs.rs/serde/1.0.104/serde/trait.Serializer.html#method.is_human_readable) and [`serde::Deserializer`](https://docs.rs/serde/1.0.104/serde/trait.Deserializer.html#method.is_human_readable) traits.
Apologies for not writing tests to pin this setting, but didn't manage to get a Deserializer instance that implements `serde::de::Deserializer`.

Set 'is_human_readable()' to false

---

README.md
rmp-serde/src/encode.rs
rmp/src/decode/mod.rs
rmp/src/marker.rs

Admittedly this PR is a bit of a guess, as ran the changes against rustc 1.40, and in the hopes that Travis will be OK with it.
This PR is also based on the assumption that the README is outdated.

Update to features of Rust 1.34.2, the latest tested one according to Travis

---

rmp-serde/src/config.rs

Fix a typo: compat -> compact.

---

rmpv/src/lib.rs

I need to consume the Utf8StringRef while returning the internal
reference for lifetime reasons. Using as_str makes it look like it is
borrowing from the Utf8StringRef instead of the source.
Sorry for the API breakage on into_str, if you want I can rename the
new method into_borrowed_str or something.

Have a way to "destructure" a Utf8StringRef.

---

rmp-serde/Cargo.toml
rmp-serde/tests/round.rs
rmpv/Cargo.toml

This updates to serde 1.0.116 to get the fix for
https://github.com/serde-rs/serde/pull/1888 , and then adds more tests,
including tests for roundtrips for every serializer configuration.

Update for serde 1.0.116 and add tests

---

rmp-serde/Cargo.toml
rmp-serde/src/config.rs
rmp-serde/src/decode.rs
rmp-serde/src/encode.rs
rmp-serde/tests/round.rs
rmpv-tests/Cargo.toml

Add a defaulted type parameter to `Deserializer` and all its auxiliary
types, threading the config ZSTs through. Delegate
`Serializer::is_human_readable` and `Deserializer::is_human_readable` to
the config. Test round-tripping for the new config variants this
introduces.

Add config to choose binary vs human-readable, for Serializer and Deserializer

---

rmp-serde/CHANGELOG.md
rmp-serde/Cargo.toml
rmp-serde/src/decode.rs
rmp-serde/src/encode.rs

This fixes #169. 128-bit values are serialised as 16 bytes, representing the binary encoding in big-endian format. I've added it behind a feature gate, so it's opt-in for those who want it. If it should be always available, I can change that.

Add serde 128-bit integer support

---

rmp-serde/CHANGELOG.md
rmp-serde/src/encode.rs
rmp-serde/tests/decode_derive.rs
rmp-serde/tests/encode_derive.rs
rmp-serde/tests/round.rs

This fixes the serialization of structs that contain fields tagged with #[serde(flatten)].
The basic idea is to write elements to another Serializer, count the elements that are
serialized, and in the end, write the counted length and the serialzed elements to the
main Serializer.
A drawback might be that such a struct cannot be written in compact representation as
serde wants to serialize it as a map.

Serializing seqs and maps of unknown length (#196) 

---

rmp-serde/CHANGELOG.md
rmp-serde/src/decode.rs
rmp-serde/tests/decode.rs
rmp-serde/tests/decode_derive.rs
rmp-serde/tests/round.rs

This should fix #245.
It seems like the fix is just to test if the marker has already been read and take it out before trying to read it from the reader.

Fix deserialization of nested Options

---

rmpv-tests/tests/decode.rs
rmpv/src/decode/mod.rs
rmpv/src/decode/value.rs
rmpv/src/decode/value_ref.rs

This should resolve #281.
The constant `MAX_DEPTH` came from running `cargo test` on the computer I developed this on. `256` was the largest power of 2 that did not cause a stack overflow, so that seemed good enough. This should allow at least 100 nested structures, if I figure correctly.
Let me know if there is anything to fix, add, or remove.

fix: add stack depth checking to rmpv

---

rmp-serde/src/decode.rs
rmp-serde/src/lib.rs
rmp-serde/tests/round.rs

Fixes #287: currently, the serde deserializer doesn't check the lengths of MapAccess or SeqAccess objects it sends to `visit_seq` and `visit_map`. This leads to a problem where certain kinds of input deserialize incorrectly. Added a fix for this bug, as well as a regression test demonstrating it.
Fixes #303: There's no reason to have a complex custom float deserializer when floats already successfully deserialize themselves from ints.
Additionally, made some obvious fixes suggested by `cargo check` and `cargo clippy`

Fix SeqAccess and MapAccess unchecked unused length; float deserialize simplification

---

rmp-serde/src/lib.rs

I just updated from v0.14 to v1.1.1 and updated uses of the deprecated fn `from_read_ref` to `from_slice`. When checking the docs for an updated format of encoding, I saw the example still uses `from_read_ref`. I suggest to update to `from_slice`.

docs(rmp-serde): update example to use from_slice
